fun main(args: Array<String>) {
    println("Question 1")
    details()
    println("------------------------")
    println("Question 2")
    var c=operation()
    c.add(1,2)
    c.add(20.0,30.0)
    c.add(10,2.0)
    c.add("Ritik","Jain")
    c.add("Ritik","Jain","Android")
    println("------------------------")
    println("Question 3")
    var s=SBI()
    s.getdetails()
    var i= ICICI()
    i.getdetails()
    var b=BOI()
    b.getdetails()
    println("------------------------")
    println("Question 4")

    val s1 = student("Ritik")
    val s2 = student("Neha")
    val s3 = student("Aman")
    s1.issuebook("English")
    s1.returnbook("Maths")

    println("------------------------")
    println("Question 5")
    val marks = 80
    println(grade(marks))
    println("------------------------")
    println("Question 6")
    list()
    println("------------------------")
    println("Question 7")
    map()
    println("------------------------")
    println("Question 8")
    set()
}